config/routes.rb
Tempo::Application.routes.draw do
  root "pages#home"
  get "about" => "pages#about"
  get "assets" => "pages#assets"
  get "athlete" => "pages#athlete"
  get "audio" => "pages#audio"
  get "event" => "pages#event"
  get "photo" => "pages#photo"
  get "video" => "pages#video"
  get "search" => "pages#search"
  get "upload" => "pages#upload"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end  

	def athlete
	end  

	def event
	end 

	def audio
	end

	def photo
	end  

	def video
	end  

	def assets
	end 

	def search
	end 

	def upload
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">

				<p>The Content Database of MXPTV</p>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to 'MXPTV DB',root_path, class:'navbar-brand' %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Events', event_path %></li>
        <li><%= link_to 'Athletes',athlete_path %></li>
        <li><%= link_to 'Content Type',assets_path %></li>
      </ul>
    
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',root_path %></li>
        <li><%= link_to 'Search',root_path %></li>
        <li><%= link_to 'Upload',root_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rice Nation</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render 'layouts/header' %>
	<div class='container'>
		<%= yield %>
	</div>	
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About ricenation.com</h1>

app/views/pages/home.html.erb
<div id="header" class="section">
	<h1>Welcome to MXPTV's Content Database</h1>
	<!-- Search Area -->
	<h3>Search MXPTV Content Database</h3>
	<form class="navbar-form navbar-left" role="search" id="db-search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search by Rider, Event, or Media Type">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
	
</div>

app/views/pages/upload.html.erb
<div id="header" class="section upload" >
	<h1>Upload Your Content Below</h1>
	<p>	
		Drag &amp; Drop your Content Here. 

	</p>
	
</div>